ALTER TABLE accounts
  ADD COLUMN IF NOT EXISTS vcpu_limit   INTEGER NOT NULL DEFAULT 8,
  ADD COLUMN IF NOT EXISTS mem_limit_mb INTEGER NOT NULL DEFAULT 12288,
  ADD COLUMN IF NOT EXISTS vm_limit     INTEGER NOT NULL DEFAULT 5;

ALTER TABLE sessions
  ADD COLUMN IF NOT EXISTS created_at BIGINT NOT NULL DEFAULT 0;
