ALTER TABLE vms ADD COLUMN base_image TEXT NOT NULL DEFAULT 'ubuntu';
ALTER TABLE vms ADD COLUMN cloned_from TEXT REFERENCES vms(id);
ALTER TABLE vms ADD COLUMN disk_usage_mb INTEGER NOT NULL DEFAULT 0;
