ALTER TABLE vms
    ADD COLUMN IF NOT EXISTS disk_mb        INTEGER NOT NULL DEFAULT 5120,
    ADD COLUMN IF NOT EXISTS bandwidth_mbps INTEGER NOT NULL DEFAULT 100;

ALTER TABLE accounts
    ADD COLUMN IF NOT EXISTS disk_limit_mb          INTEGER NOT NULL DEFAULT 51200,
    ADD COLUMN IF NOT EXISTS bandwidth_limit_mbps   INTEGER NOT NULL DEFAULT 100;
