// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: agent.proto

package agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateVmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Subdomain     string                 `protobuf:"bytes,4,opt,name=subdomain,proto3" json:"subdomain,omitempty"`
	Image         string                 `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	Vcpus         float64                `protobuf:"fixed64,6,opt,name=vcpus,proto3" json:"vcpus,omitempty"`
	MemoryMb      int32                  `protobuf:"varint,7,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	ExposedPort   int32                  `protobuf:"varint,8,opt,name=exposed_port,json=exposedPort,proto3" json:"exposed_port,omitempty"`
	IpAddress     string                 `protobuf:"bytes,9,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVmRequest) Reset() {
	*x = CreateVmRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVmRequest) ProtoMessage() {}

func (x *CreateVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVmRequest.ProtoReflect.Descriptor instead.
func (*CreateVmRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *CreateVmRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *CreateVmRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CreateVmRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateVmRequest) GetSubdomain() string {
	if x != nil {
		return x.Subdomain
	}
	return ""
}

func (x *CreateVmRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CreateVmRequest) GetVcpus() float64 {
	if x != nil {
		return x.Vcpus
	}
	return 0
}

func (x *CreateVmRequest) GetMemoryMb() int32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *CreateVmRequest) GetExposedPort() int32 {
	if x != nil {
		return x.ExposedPort
	}
	return 0
}

func (x *CreateVmRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

type CreateVmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVmResponse) Reset() {
	*x = CreateVmResponse{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVmResponse) ProtoMessage() {}

func (x *CreateVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVmResponse.ProtoReflect.Descriptor instead.
func (*CreateVmResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *CreateVmResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CreateVmResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StartVmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartVmRequest) Reset() {
	*x = StartVmRequest{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVmRequest) ProtoMessage() {}

func (x *StartVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVmRequest.ProtoReflect.Descriptor instead.
func (*StartVmRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *StartVmRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

type StartVmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartVmResponse) Reset() {
	*x = StartVmResponse{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVmResponse) ProtoMessage() {}

func (x *StartVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVmResponse.ProtoReflect.Descriptor instead.
func (*StartVmResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *StartVmResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *StartVmResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StopVmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopVmRequest) Reset() {
	*x = StopVmRequest{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopVmRequest) ProtoMessage() {}

func (x *StopVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopVmRequest.ProtoReflect.Descriptor instead.
func (*StopVmRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *StopVmRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

type StopVmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopVmResponse) Reset() {
	*x = StopVmResponse{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopVmResponse) ProtoMessage() {}

func (x *StopVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopVmResponse.ProtoReflect.Descriptor instead.
func (*StopVmResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *StopVmResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *StopVmResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteVmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVmRequest) Reset() {
	*x = DeleteVmRequest{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVmRequest) ProtoMessage() {}

func (x *DeleteVmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVmRequest.ProtoReflect.Descriptor instead.
func (*DeleteVmRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteVmRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

type DeleteVmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVmResponse) Reset() {
	*x = DeleteVmResponse{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVmResponse) ProtoMessage() {}

func (x *DeleteVmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVmResponse.ProtoReflect.Descriptor instead.
func (*DeleteVmResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteVmResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *DeleteVmResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TakeSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TakeSnapshotRequest) Reset() {
	*x = TakeSnapshotRequest{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TakeSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeSnapshotRequest) ProtoMessage() {}

func (x *TakeSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeSnapshotRequest.ProtoReflect.Descriptor instead.
func (*TakeSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *TakeSnapshotRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *TakeSnapshotRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type TakeSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	SnapId        string                 `protobuf:"bytes,3,opt,name=snap_id,json=snapId,proto3" json:"snap_id,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TakeSnapshotResponse) Reset() {
	*x = TakeSnapshotResponse{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TakeSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeSnapshotResponse) ProtoMessage() {}

func (x *TakeSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeSnapshotResponse.ProtoReflect.Descriptor instead.
func (*TakeSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *TakeSnapshotResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *TakeSnapshotResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TakeSnapshotResponse) GetSnapId() string {
	if x != nil {
		return x.SnapId
	}
	return ""
}

func (x *TakeSnapshotResponse) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type RestoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	SnapId        string                 `protobuf:"bytes,2,opt,name=snap_id,json=snapId,proto3" json:"snap_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreRequest) Reset() {
	*x = RestoreRequest{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRequest) ProtoMessage() {}

func (x *RestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRequest.ProtoReflect.Descriptor instead.
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *RestoreRequest) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *RestoreRequest) GetSnapId() string {
	if x != nil {
		return x.SnapId
	}
	return ""
}

type RestoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreResponse) Reset() {
	*x = RestoreResponse{}
	mi := &file_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreResponse) ProtoMessage() {}

func (x *RestoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreResponse.ProtoReflect.Descriptor instead.
func (*RestoreResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (x *RestoreResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RestoreResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{12}
}

type AgentEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Event         string                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"` // "started" | "stopped" | "crashed" | "snapshot_taken"
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentEvent) Reset() {
	*x = AgentEvent{}
	mi := &file_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEvent) ProtoMessage() {}

func (x *AgentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEvent.ProtoReflect.Descriptor instead.
func (*AgentEvent) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{13}
}

func (x *AgentEvent) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *AgentEvent) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *AgentEvent) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *AgentEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ConsoleInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmId          string                 `protobuf:"bytes,1,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"` // set only in the first frame to identify the target VM
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsoleInput) Reset() {
	*x = ConsoleInput{}
	mi := &file_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleInput) ProtoMessage() {}

func (x *ConsoleInput) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleInput.ProtoReflect.Descriptor instead.
func (*ConsoleInput) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{14}
}

func (x *ConsoleInput) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *ConsoleInput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ConsoleOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsoleOutput) Reset() {
	*x = ConsoleOutput{}
	mi := &file_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleOutput) ProtoMessage() {}

func (x *ConsoleOutput) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleOutput.ProtoReflect.Descriptor instead.
func (*ConsoleOutput) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{15}
}

func (x *ConsoleOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"` // gRPC address control-plane uses to reach this agent
	VcpuTotal     uint32                 `protobuf:"varint,4,opt,name=vcpu_total,json=vcpuTotal,proto3" json:"vcpu_total,omitempty"`
	MemTotalMb    uint32                 `protobuf:"varint,5,opt,name=mem_total_mb,json=memTotalMb,proto3" json:"mem_total_mb,omitempty"`
	ImagesDir     string                 `protobuf:"bytes,6,opt,name=images_dir,json=imagesDir,proto3" json:"images_dir,omitempty"`
	OverlayDir    string                 `protobuf:"bytes,7,opt,name=overlay_dir,json=overlayDir,proto3" json:"overlay_dir,omitempty"`
	SnapshotDir   string                 `protobuf:"bytes,8,opt,name=snapshot_dir,json=snapshotDir,proto3" json:"snapshot_dir,omitempty"`
	KernelPath    string                 `protobuf:"bytes,9,opt,name=kernel_path,json=kernelPath,proto3" json:"kernel_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{16}
}

func (x *RegisterRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterRequest) GetVcpuTotal() uint32 {
	if x != nil {
		return x.VcpuTotal
	}
	return 0
}

func (x *RegisterRequest) GetMemTotalMb() uint32 {
	if x != nil {
		return x.MemTotalMb
	}
	return 0
}

func (x *RegisterRequest) GetImagesDir() string {
	if x != nil {
		return x.ImagesDir
	}
	return ""
}

func (x *RegisterRequest) GetOverlayDir() string {
	if x != nil {
		return x.OverlayDir
	}
	return ""
}

func (x *RegisterRequest) GetSnapshotDir() string {
	if x != nil {
		return x.SnapshotDir
	}
	return ""
}

func (x *RegisterRequest) GetKernelPath() string {
	if x != nil {
		return x.KernelPath
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{17}
}

func (x *RegisterResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	RunningVmIds  []string               `protobuf:"bytes,2,rep,name=running_vm_ids,json=runningVmIds,proto3" json:"running_vm_ids,omitempty"`
	VcpuUsed      uint32                 `protobuf:"varint,3,opt,name=vcpu_used,json=vcpuUsed,proto3" json:"vcpu_used,omitempty"`
	MemUsedMb     uint32                 `protobuf:"varint,4,opt,name=mem_used_mb,json=memUsedMb,proto3" json:"mem_used_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{18}
}

func (x *HeartbeatRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *HeartbeatRequest) GetRunningVmIds() []string {
	if x != nil {
		return x.RunningVmIds
	}
	return nil
}

func (x *HeartbeatRequest) GetVcpuUsed() uint32 {
	if x != nil {
		return x.VcpuUsed
	}
	return 0
}

func (x *HeartbeatRequest) GetMemUsedMb() uint32 {
	if x != nil {
		return x.MemUsedMb
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{19}
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x05agent\"\x82\x02\n" +
	"\x0fCreateVmRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1c\n" +
	"\tsubdomain\x18\x04 \x01(\tR\tsubdomain\x12\x14\n" +
	"\x05image\x18\x05 \x01(\tR\x05image\x12\x14\n" +
	"\x05vcpus\x18\x06 \x01(\x01R\x05vcpus\x12\x1b\n" +
	"\tmemory_mb\x18\a \x01(\x05R\bmemoryMb\x12!\n" +
	"\fexposed_port\x18\b \x01(\x05R\vexposedPort\x12\x1d\n" +
	"\n" +
	"ip_address\x18\t \x01(\tR\tipAddress\"8\n" +
	"\x10CreateVmResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"%\n" +
	"\x0eStartVmRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"7\n" +
	"\x0fStartVmResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"$\n" +
	"\rStopVmRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"6\n" +
	"\x0eStopVmResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"&\n" +
	"\x0fDeleteVmRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\"8\n" +
	"\x10DeleteVmResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"@\n" +
	"\x13TakeSnapshotRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"t\n" +
	"\x14TakeSnapshotResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x17\n" +
	"\asnap_id\x18\x03 \x01(\tR\x06snapId\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\">\n" +
	"\x0eRestoreRequest\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x17\n" +
	"\asnap_id\x18\x02 \x01(\tR\x06snapId\"7\n" +
	"\x0fRestoreResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x0e\n" +
	"\fWatchRequest\"m\n" +
	"\n" +
	"AgentEvent\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x14\n" +
	"\x05event\x18\x02 \x01(\tR\x05event\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"7\n" +
	"\fConsoleInput\x12\x13\n" +
	"\x05vm_id\x18\x01 \x01(\tR\x04vmId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"#\n" +
	"\rConsoleOutput\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x9d\x02\n" +
	"\x0fRegisterRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"vcpu_total\x18\x04 \x01(\rR\tvcpuTotal\x12 \n" +
	"\fmem_total_mb\x18\x05 \x01(\rR\n" +
	"memTotalMb\x12\x1d\n" +
	"\n" +
	"images_dir\x18\x06 \x01(\tR\timagesDir\x12\x1f\n" +
	"\voverlay_dir\x18\a \x01(\tR\n" +
	"overlayDir\x12!\n" +
	"\fsnapshot_dir\x18\b \x01(\tR\vsnapshotDir\x12\x1f\n" +
	"\vkernel_path\x18\t \x01(\tR\n" +
	"kernelPath\"\"\n" +
	"\x10RegisterResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x8e\x01\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12$\n" +
	"\x0erunning_vm_ids\x18\x02 \x03(\tR\frunningVmIds\x12\x1b\n" +
	"\tvcpu_used\x18\x03 \x01(\rR\bvcpuUsed\x12\x1e\n" +
	"\vmem_used_mb\x18\x04 \x01(\rR\tmemUsedMb\"\x13\n" +
	"\x11HeartbeatResponse2\xfa\x03\n" +
	"\tHostAgent\x12;\n" +
	"\bCreateVm\x12\x16.agent.CreateVmRequest\x1a\x17.agent.CreateVmResponse\x128\n" +
	"\aStartVm\x12\x15.agent.StartVmRequest\x1a\x16.agent.StartVmResponse\x125\n" +
	"\x06StopVm\x12\x14.agent.StopVmRequest\x1a\x15.agent.StopVmResponse\x12;\n" +
	"\bDeleteVm\x12\x16.agent.DeleteVmRequest\x1a\x17.agent.DeleteVmResponse\x12G\n" +
	"\fTakeSnapshot\x12\x1a.agent.TakeSnapshotRequest\x1a\x1b.agent.TakeSnapshotResponse\x12@\n" +
	"\x0fRestoreSnapshot\x12\x15.agent.RestoreRequest\x1a\x16.agent.RestoreResponse\x127\n" +
	"\vWatchEvents\x12\x13.agent.WatchRequest\x1a\x11.agent.AgentEvent0\x01\x12>\n" +
	"\rStreamConsole\x12\x13.agent.ConsoleInput\x1a\x14.agent.ConsoleOutput(\x010\x012\x8b\x01\n" +
	"\fControlPlane\x12;\n" +
	"\bRegister\x12\x16.agent.RegisterRequest\x1a\x17.agent.RegisterResponse\x12>\n" +
	"\tHeartbeat\x12\x17.agent.HeartbeatRequest\x1a\x18.agent.HeartbeatResponseB+Z)github.com/spwn/spwn/services/proto/agentb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_agent_proto_goTypes = []any{
	(*CreateVmRequest)(nil),      // 0: agent.CreateVmRequest
	(*CreateVmResponse)(nil),     // 1: agent.CreateVmResponse
	(*StartVmRequest)(nil),       // 2: agent.StartVmRequest
	(*StartVmResponse)(nil),      // 3: agent.StartVmResponse
	(*StopVmRequest)(nil),        // 4: agent.StopVmRequest
	(*StopVmResponse)(nil),       // 5: agent.StopVmResponse
	(*DeleteVmRequest)(nil),      // 6: agent.DeleteVmRequest
	(*DeleteVmResponse)(nil),     // 7: agent.DeleteVmResponse
	(*TakeSnapshotRequest)(nil),  // 8: agent.TakeSnapshotRequest
	(*TakeSnapshotResponse)(nil), // 9: agent.TakeSnapshotResponse
	(*RestoreRequest)(nil),       // 10: agent.RestoreRequest
	(*RestoreResponse)(nil),      // 11: agent.RestoreResponse
	(*WatchRequest)(nil),         // 12: agent.WatchRequest
	(*AgentEvent)(nil),           // 13: agent.AgentEvent
	(*ConsoleInput)(nil),         // 14: agent.ConsoleInput
	(*ConsoleOutput)(nil),        // 15: agent.ConsoleOutput
	(*RegisterRequest)(nil),      // 16: agent.RegisterRequest
	(*RegisterResponse)(nil),     // 17: agent.RegisterResponse
	(*HeartbeatRequest)(nil),     // 18: agent.HeartbeatRequest
	(*HeartbeatResponse)(nil),    // 19: agent.HeartbeatResponse
}
var file_agent_proto_depIdxs = []int32{
	0,  // 0: agent.HostAgent.CreateVm:input_type -> agent.CreateVmRequest
	2,  // 1: agent.HostAgent.StartVm:input_type -> agent.StartVmRequest
	4,  // 2: agent.HostAgent.StopVm:input_type -> agent.StopVmRequest
	6,  // 3: agent.HostAgent.DeleteVm:input_type -> agent.DeleteVmRequest
	8,  // 4: agent.HostAgent.TakeSnapshot:input_type -> agent.TakeSnapshotRequest
	10, // 5: agent.HostAgent.RestoreSnapshot:input_type -> agent.RestoreRequest
	12, // 6: agent.HostAgent.WatchEvents:input_type -> agent.WatchRequest
	14, // 7: agent.HostAgent.StreamConsole:input_type -> agent.ConsoleInput
	16, // 8: agent.ControlPlane.Register:input_type -> agent.RegisterRequest
	18, // 9: agent.ControlPlane.Heartbeat:input_type -> agent.HeartbeatRequest
	1,  // 10: agent.HostAgent.CreateVm:output_type -> agent.CreateVmResponse
	3,  // 11: agent.HostAgent.StartVm:output_type -> agent.StartVmResponse
	5,  // 12: agent.HostAgent.StopVm:output_type -> agent.StopVmResponse
	7,  // 13: agent.HostAgent.DeleteVm:output_type -> agent.DeleteVmResponse
	9,  // 14: agent.HostAgent.TakeSnapshot:output_type -> agent.TakeSnapshotResponse
	11, // 15: agent.HostAgent.RestoreSnapshot:output_type -> agent.RestoreResponse
	13, // 16: agent.HostAgent.WatchEvents:output_type -> agent.AgentEvent
	15, // 17: agent.HostAgent.StreamConsole:output_type -> agent.ConsoleOutput
	17, // 18: agent.ControlPlane.Register:output_type -> agent.RegisterResponse
	19, // 19: agent.ControlPlane.Heartbeat:output_type -> agent.HeartbeatResponse
	10, // [10:20] is the sub-list for method output_type
	0,  // [0:10] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
